### ISSUE TITLE
ContentService

### ISSUE THREAD

**Issue by curtisblackwell** [roobottom/statamic-add-on-archive#1]
I won't pretend to have looked all that closely at the source, but I was surprised to see that the template code required both the `{{ archive:xxx }}` tag and `{{ entries:listing }}`.

If you want to handle it w/o the `{{ entries:listing }}`, check out `pi.entries.php` and look at how it uses `app/core/content/contentservice.php`.

This is awesome, though. I'll definitely try it out next time I need to create an entry archive.

**Comment by roobottom** [comment]
Hey Curtis. Thanks for the suggestion, but this plugin is deigned to fetch a list of available years and months only — not to bring back any information about the posts therein. I think it's probably better to use the built in functionality to return post data itself.

Unless there's another reason you think this should bring back the post data?

**Comment by curtisblackwell** [comment]
I thought that was the point. Does it serve a purpose without fetching entries? If so, then I'd say it makes sense as is.

**Comment by roobottom** [comment]
I think it's best like this... but happy to hear use cases that require more functionality.

**Comment by curtisblackwell** [comment]
Generally speaking, I just think usage should be as simple/clean as possible. Using contentservice would fall under that category here, unless there's a use case w/o using an entries tag.
